# Application port
server:
  port: 8091

# Application name
spring:
  application:
    name: esd-aom-gateway

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Eureka settings
eureka:
  instance:
    instance-id=${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka